### PR TITLE
Use server's filter state to check whether to update ComboBox filter.

### LINKED ISSUE #10624: ComboBox: All items are not present
Hi,

On Vaadin 8.3.1

```
ComboBox<String> comboBox = new ComboBox<>();
comboBox.setItems(Arrays.asList("aa", "ab", "b", "c"));
mainLayout.addComponent(comboBox);

Button button1 = new Button("hide");
button1.addClickListener(event1 -> comboBox.setVisible(false));
mainLayout.addComponent(button1);

Button button = new Button("set null and show");
button.addClickListener(event1 -> {
    comboBox.setValue(null);
    comboBox.setVisible(true);
});
mainLayout.addComponent(button);
```

To reproduce:
- Tape "a" on field
- Press "hide"
- Press "set null and show"
- Look at the list => The list doesn't contain all items but only items that contain "a" even if the field is null

Thanks,

### PR DESCRIPTION
**Pull request by Ansku**
Fixes #10624

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10630)

### CODE REVIEW

File: shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java [hunk 1]
```diff
@@ -100,4 +100,9 @@
      */
     public String selectedItemIcon;
 
+    /**
+     * Filter string that is currently in use in the suggestion listing.
```
Comment (tsuoanttila) [inline shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java]: missing since tag

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10630#-:-L6MmY062Wo34NNcMFyP:bnfp4nl)*
